on: [push]

jobs:
  collect-labels:
    runs-on: ubuntu-latest
    name: Coolect labels from release note
    steps:
      - name: Collect
        id: collect
        uses: hankei6km/collect-labels-from-release-note@v0.1.16
        with:
          token: ${{ secrets.GITHUB_TOKEN}}
          repository: hankei6km/gas-md2html
          tag_name: v0.5.0
      - name: Print
        run: echo "${LABELS}"
        env:
          LABELS: ${{ steps.collect.outputs.labels }}
      - name: Contains as string
        run: echo "${{ contains(steps.collect.outputs.labels, 'ing","tes') }}"
      - name: Contains as array(false)
        run: echo "${{ contains(toJson(steps.collect.outputs.labels), 'ing","tes') }}"
      - name: Contains as array(true)
        run: echo "${{ contains(toJson(steps.collect.outputs.labels), 'testing') }}"
      - name: Collect(not exist)
        id: collect_not_exist
        continue-on-error: true
        uses: hankei6km/collect-labels-from-release-note@v0.1.16
        with:
          token: ${{ secrets.GITHUB_TOKEN}}
          repository: hankei6km/gas-md2html
          tag_name: dummy
      - name: Print(not exist)
        run: echo "${LABELS}"
        env:
          LABELS: ${{ toJSON(steps.collect_not_exist.outputs.*) }}
